version: '3'

services:

  # caddy
  proxy:
    build:
      context: ./proxy
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - caddy_config:/config
    entrypoint: ["caddy", "-agree", "-http-port", "8080", "-https-port", "8443", "-conf", "/config/Caddyfile", "-log", "stdout"]


  # webhook:
  #   - subscription manager
  #   - webhook receiver
  #   - url shortner/redirection provider
  #
  webhook:
    build:
      context: ./webhook
      args:
        RUBY_VERSION: 2.6.0-rc2-alpine3.8
    env_file:
      - .webhook.env
    depends_on:
      - mqtt

  # mqtt server public
  mqtt:
    build:
      context: ./mqtt

    ports:
      - "8883:8883"
      - "9001:9001"
    volumes:
      - mqtt_data:/data:consistent

  # fetch streams:
  # needs to access YouTube with the same IP as the iOS device will do later(!)
  downloader:
    build:
      context: ./downloader
      args:
        RUBY_VERSION: 2.6.0-rc2-alpine3.8
    env_file:
      - .downloader.env
    volumes:
      - video_data:/data:consistent
    depends_on:
      - mqtt

  downloader-syncthing:
    build:
      context: ./downloader-syncthing
    restart: always
    ports:
      - "127.0.0.1:8384:8384"
      - "22000:22000"
      - "21027:21027/udp"
    volumes:
      - video_data:/data

volumes:
  video_data:
  mqtt_data:
  caddy_config:
