# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'mail'
gem 'mixlib-shellout'
gem 'mqtt'

group :development do
  gem 'rubocop'
end
